---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/ManigandanKannan/pcf-attendee-service-code   
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.system.cumuluslabs.io/        
    username: {{cf-user}}
    password: {{cf-password}}
    organization: mkannan-PAL-Dec11    
    space: sandbox         
    skip_cert_check: false

jobs:
- name: build
  public: true
  plan:
  - get: attendee-service
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

